baseURL = "/"
languageCode = "en-us"
title = "John T Gray"

enableRobotsTXT = true
disableAliases = true

assetDir= "static"

[params]
disallow_search_engines = false # set robots.txt to disallow everything

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[[menu.main]]
  name = "About"
  weight = 1
  url = "/about/"

[[menu.main]]
  name = "Inquiries"
  weight = 2
  url = "/inquiries/"

[[menu.main]]
  name = "Portfolio"
  weight = 3
  url = "/portfolio/"

[[menu.footer]]
  name = "Home"
  weight = 1
  url = "/"

[[menu.footer]]
  name = "Message"
  weight = 2
  url = "/message"

[[menu.footer]]
  name = "Github"
  weight = 3
  url = "https://github.com/jtgry"

[[menu.footer]]
  name = "Instagram"
  weight = 4
  url = "https://www.instagram.com/jtgry/"

[related]
threshold = 80
includeNewer = true
toLower = false
[[related.indices]]
name = "title"
weight = 100
[[related.indices]]
name = "category"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"