baseURL = "/"
languageCode = "en-us"
title = "John T Gray"

enableRobotsTXT = true
disableAliases = true

assetDir= "static"

googleAnaylitcs = "UA-114350169-1"

[params]
disallow_search_engines = false # set robots.txt to disallow everything
description = "With over 8 years of professional IT experience, I have a passion for creating solutions using technology. Although I specialize in Web Design & Development, I also consult with businesses in multiple areas to improve their efficiency and productivity."
profileimage = "/uploads/tyler.jpg"
# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[[menu.main]]
  name = "About"
  weight = 1
  url = "/#about"

[[menu.main]]
  name = "Portfolio"
  weight = 3
  url = "/#portfolio"

[[menu.footer]]
  name = "Home"
  weight = 1
  url = "/"

[[menu.footer]]
  name = "Message"
  weight = 2
  url = "/contact"

[[menu.footer]]
  name = "Github"
  weight = 3
  url = "https://github.com/jtgry"

[[menu.footer]]
  name = "Instagram"
  weight = 4
  url = "https://www.instagram.com/jtgry/"


